/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/login/login" |
       "/pages/ai-workbench/index" |
       "/pages/create/index" |
       "/pages/detail/index" |
       "/pages/index/index" |
       "/pages/ledger/index" |
       "/pages/messages/index" |
       "/pages/mine/index" |
       "/pages/mine-initiated/index" |
       "/pages/profile/index" |
       "/pages/settings/index" |
       "/pages/task-list/index" |
       "/pages/workbench/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
